name: Package Helm Chart

on:
  push:
    paths:
      - 'charts/**'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Package Helm chart
        run: |
          for chart_dir in charts/*; do
            if [ -d "$chart_dir" ]; then
              helm package "$chart_dir"
            fi
          done

      - name: Create or update helm index
        run: helm repo index . --url "https://beerdevs.github.io/helm-charts"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
