name: Package Helm Chart

on:
  push:
    paths:
      - 'charts/**'
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code and verify branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Package charts
        run: |
          echo "CURRENT PATH:" $(pwd)
          for chart_dir in charts/*; do
            if [ -d "$chart_dir" ]; then
              helm package "$chart_dir"
            fi
          done

      - name: Prepare gh-pages branch for deployment
        run: |
          # Checkout de gh-pages en un directorio temporal para no mezclar
          git clone --depth 1 https://github.com/beerdevs/helm-charts.git temp-gh-pages
          
          # Copiar los paquetes viejos y el índice
          cp temp-gh-pages/*.tgz . 2>/dev/null || :
          cp temp-gh-pages/index.yaml . 2>/dev/null || :
          
          # Actualizar el índice con los nuevos paquetes
          helm repo index . --url "https://beerdevs.github.io/helm-charts" --merge index.yaml
          
          # Limpiar el directorio temporal
          rm -rf temp-gh-pages
                    
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
