name: Package Helm Chart

on:
  push:
    paths:
      - 'azdo-app-helm-chart/**'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Package Helm chart
        run: |
          helm package azdo-app-helm-chart